[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "src/twitch_bot/__main__.py"

[project]
dynamic = ['version']
name = "twitch-bot"
description = "A twitch bot"
readme = "README.md"
license = {file = "LICENSE"}
keywords = ["twitch"]

requires-python = ">= 3.8"

[project.urls]
Homepage = "https://github.com/TheCrunching/python-twitch-bot"
Documentation = "https://github.com/TheCrunching/python-twitch-bot/blob/main/README.md"
repository = "https://github.com/TheCrunching/python-twitch-bot"
Changelog = "https://github.com/TheCrunching/python-twitch-bot/blob/main/CHANGELOG.md"

[project.scripts]
twitch-bot = "twitch_bot.__main__:main"
